#Test with: http://editor.swagger.io/

swagger: '2.0'
info:
  version: 1.0.0
  title: Vanellope
  description: Microservice of sign up and log in deploy on Ruby on Rails + Postgres
  license:
    name: Software Architecture, 2019-I
host: 127.0.0.1:3001
basePath: /resources
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /user/create:
    post:
      summary: Creates a new user
      operationId: createUser
      parameters:
        - name: user
          in: body
          required: true
          description: User Object with the correct parameters
          schema:
            $ref: '#/definitions/NewUser'
      responses:
        '201':
          description: Created
        '406':
          description: Not Acceptable (Invalid Params)
        '500':
          description: Internal Server Error

  /users:
    get:
      summary: Returns all Users
      operationId: getAllusers
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/UsersList'
        '406':
          description: Not Acceptable (Invalid Params)
        '500':
          description: Internal Server Error

  /user:
    get:
      summary: Returns a user with the given id
      operationId: getUserByEmail
      parameters:
        - name: email
          in: body
          description: The user with that email to be returned
          required: true
          schema:
            $ref: '#/definitions/GetUser'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/GetUser200'
        '406':
            description: Not Acceptable (Invalid Params)
        '500':
          description: Internal Server Error


    put:
      summary: Updates a user with the given id
      operationId: updateUser
      parameters:
        - name: user
          in: body
          description: Updates user fields by getting the id
          required: true
          schema:
            $ref: '#/definitions/UpdateUser'
      responses:
        '202':
          description: Aceptable        
        '406':
            description: Not Acceptable (Invalid Params)
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error

    delete:
      summary: Deletes a course with the given code
      operationId: deleteCourse
      parameters:
        - name: id
          in: body
          description: Delete the user by obtaining the id
          required: true
          schema:
            $ref: '#/definitions/IdUser'
      responses:
        '200':
          description: Ok
        '404':
          description: Not Found
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
  
  /users/login:
    post:
      summary: Creates a new user session
      operationId: createNewUserSession
      parameters:
        - name: user
          in: body
          required: true
          description: Log in of the user with the correct parameters
          schema:
            $ref: '#/definitions/LogInUser'
      responses:
        '200':
          description: Ok
        '406':
          description: Not Acceptable (Invalid Params)
        '404':
          description: Not found
        '500':
          description: Internal Server Error

  /users/logout:
    delete:
      summary: Log out of a user session
      operationId: deleteUserSession
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

definitions:
  #NewUser
  NewUser:
    type: object
    properties:
      user:
        type: object
        properties:
          name:
            type: string
          last_name:
            type: string
          email:
            type: string
          password:
            type: string
          password_confirmation:
            type: string

  #GetUser
  GetUser:
    type: object
    properties:
      email:
        type: string


  #IdUser
  IdUser:
    type: object
    properties:
      id:
        type: string

  #UpdateUser
  UpdateUser:
    type: object
    properties:
      user:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
          last_name:
            type: string
          email:
            type: string
          password:
            type: string
          password_confirmation:
            type: string

  # User
  User:
    type: object
    properties:
      name:
        type: string
      last_name:
        type: string
      email:
        type: string

  # User
  GetUser200:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      last_name:
        type: string
      email:
        type: string

  UsersList:
    type: object
    required:
      - total
      - list
    properties:
      total:
        type: number
      list:
        type: array
        items:
          $ref: '#/definitions/User'

  #LogInUser
  LogInUser:
    type: object
    properties:
      user:
        type: object
        properties:
          email:
            type: string
          password:
            type: string


# Errors
  ErrorModel:
    type: object
    properties:
      name:
        type: string
      last_name:
        type: string
      email:
        type: 'string'
      password:
        type: string
      password_confirmation:
        type: string