version: '2'

services:
  vanellope-db1:
    image: mysql:5.7
    ports:
      - "3317:3306"
    container_name: vanellopeContentDB
    environment:
      MYSQL_ROOT_PASSWORD: yotas
      MYSQL_USER: eagleun
      MYSQL_PASSWORD: yotas
      MYSQL_DATABASE: users
      MYSQL_HOST: vanellope-db1
    volumes:
      - 'vanellope_data:/var/lib/mysql'

  vanellope-ms:
    build: .
    #normal execution without modification about database
    command: bash -c "gem uninstall bundler && gem update bundler && bundler update --bundler && bundler install && rails db:migrate && rails s -p 3001 -b '0.0.0.0'"
    #normal execution with restart database without seeds
    #command: bash -c "gem uninstall bundler && gem update bundler && bundler update --bundler && bundler install && rails db:drop && rails db:create && rails db:setup && rails db:migrate && rails s -p 3001 -b '0.0.0.0'"
    #normal execution with restart database with seeds
    #command: bash -c "gem uninstall bundler && gem update bundler && bundler update --bundler && bundler install && rails db:drop && rails db:create && rails db:setup && rails db:migrate && rails db:seed && rails s -p 3001 -b '0.0.0.0'"
    ports:
      - '3001:3001'
    depends_on:
      - vanellope-db1

volumes:
  vanellope_data: {}
