version: '2'

services:
  vanellope-db:
    image: postgres:9.6-alpine
    container_name: vanellopeContent
    ports:
      - '25432:5432'
    environment:
      - POSTGRES_USER=usersms
      - POSTGRES_PASSWORD=yiuPh9eipiu2la9ie8gaifec
      - POSTGRES_DB=exeggcute
    volumes:
      - 'vanellope_data:/var/lib/postgresql/data'

  vanellope-ms:
    build: .
    #normal execution without modification about database
    command: bash -c "gem uninstall bundler && gem update bundler && bundler update --bundler && bundler install && rails db:migrate && rails s -p 3001 -b '0.0.0.0'"
    #normal execution with restart database without seeds
    #command: bash -c "gem uninstall bundler && gem update bundler && bundler update --bundler && bundler install && rails db:drop && rails db:create && rails db:setup && rails db:migrate && rails s -p 3001 -b '0.0.0.0'"
    #normal execution with restart database with seeds
    #command: bash -c "gem uninstall bundler && gem update bundler && bundler update --bundler && bundler install && rails db:drop && rails db:create && rails db:setup && rails db:migrate && rails db:seed && rails s -p 3001 -b '0.0.0.0'"
    ports:
      - '3001:3001'
    depends_on:
      - vanellope-db

volumes:
  vanellope_data: